<?php

declare(strict_types=1);

namespace Cast\Support;

/**
 * Turns markdown files into the data the documentation viewer (`Resources/docs/index.html`) shows.
 *
 * Each page is a `.md` file whose first lines may be front matter:
 *
 *   ---
 *   title: Getting started
 *   section: Start
 *   order: 1
 *   description: One line shown under the title and in search results.
 *   ---
 *
 * (Without a title the first `# heading` is used; without a section the page goes under "Reference".) A README is split into one page per
 * `## heading`, placed by `docs/_meta.json` ("readme": {"Heading": ["Section", order]}). Links between pages (`GETTING-STARTED.md`,
 * `../README.md#anchor`, `#anchor`) are rewritten to viewer links (`#/page/anchor`). The result is `data.js`: `window.CAST_DOCS = {...}`.
 * Markdown is rendered in the browser, so the viewer needs nothing but two static files.
 */
final class DocsBuilder
{
    /** @var list<array{slug: string, title: string, section: string, order: int, description: string, source: string, md: string}> */
    private array $pages = [];
    /** @var array<string, string> heading anchor => page slug */
    private array $anchors = [];

    /**
     * @param string $source   folder with the `.md` pages
     * @param string|null $readme  a README to split into pages (or null)
     * @param string|null $meta    `_meta.json` (title, section order, how to place README headings); default `<source>/_meta.json`
     * @return array{title: string, version: string, sections: list<string>, pages: list<array<string, mixed>>}
     */
    public function build(string $source, ?string $readme = null, ?string $meta = null, string $version = ''): array
    {
        $meta = $this->meta($meta ?? rtrim($source, '/\\') . '/_meta.json');
        $this->pages = [];
        $this->anchors = [];

        foreach (glob(rtrim($source, '/\\') . '/*.md') ?: [] as $file) {
            $page = $this->page($file, (string) file_get_contents($file), $meta['root'] ?? dirname($source));
            if ($page !== null) $this->pages[] = $page;
        }
        if ($readme !== null && is_file($readme)) {
            foreach ($this->splitReadme((string) file_get_contents($readme), $meta, basename($readme)) as $page) $this->pages[] = $page;
        }

        $order = array_flip($meta['sections'] ?? []);
        usort($this->pages, fn($a, $b) => [$order[$a['section']] ?? 999, $a['order'], $a['title']] <=> [$order[$b['section']] ?? 999, $b['order'], $b['title']]);

        // anchors of every heading, so a link to `#using-another-orm` finds its page
        foreach ($this->pages as $page) {
            foreach ($this->headings($page['md']) as $heading) $this->anchors[self::slug($heading)] ??= $page['slug'];
        }
        $pages = array_map(function (array $p) {
            $p['md'] = $this->rewriteLinks($p['md'], $p['slug']);
            return $p;
        }, $this->pages);

        $sections = array_values(array_unique(array_merge($meta['sections'] ?? [], array_column($pages, 'section'))));
        return ['title' => (string) ($meta['title'] ?? 'Documentation'), 'version' => $version, 'sections' => $sections, 'pages' => $pages];
    }

    /** The `data.js` file for the viewer. */
    public function render(array $data): string
    {
        return "// Generated by `php cast docs:build` from the markdown files. Do not edit: change the .md files and build again.\n"
            . 'window.CAST_DOCS = ' . json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT | JSON_HEX_TAG) . ";\n";
    }

    /** GitHub-style anchor for a heading: lower case, no punctuation, spaces to hyphens. Mirrored in the viewer's JavaScript. */
    public static function slug(string $heading): string
    {
        $text = strtolower(trim((string) preg_replace('/[`*_~]/', '', $heading)));
        $text = (string) preg_replace('/[^a-z0-9 _\-]/', '', $text);
        return trim((string) preg_replace('/ /', '-', $text), '-');
    }

    /** @return array{title?: string, sections?: list<string>, readme?: array<string, array{0: string, 1?: int}>, root?: string} */
    private function meta(string $file): array
    {
        $meta = is_file($file) ? json_decode((string) file_get_contents($file), true) : null;
        return is_array($meta) ? $meta : [];
    }

    /** @return array{front: array<string, string>, body: string} */
    public static function frontMatter(string $text): array
    {
        $text = str_replace("\r\n", "\n", $text);
        if (!preg_match('/\A---\n(.*?)\n---\n?(.*)\z/s', $text, $m)) return ['front' => [], 'body' => $text];
        $front = [];
        foreach (explode("\n", $m[1]) as $line) {
            if (preg_match('/^([A-Za-z_-]+):\s*(.*)$/', $line, $kv)) $front[strtolower($kv[1])] = trim($kv[2], " \t\"'");
        }
        return ['front' => $front, 'body' => $m[2]];
    }

    private function page(string $file, string $text, string $root): ?array
    {
        $parts = self::frontMatter($text);
        $body = ltrim($parts['body'], "\n");
        if (($parts['front']['draft'] ?? '') === 'true') return null;
        $title = $parts['front']['title'] ?? (preg_match('/^# (.+)$/m', $body, $m) ? trim($m[1]) : ucfirst(strtolower(str_replace(['-', '_'], ' ', basename($file, '.md')))));
        $body = (string) preg_replace('/\A# .+\n+/', '', $body, 1);   // the viewer shows the title itself
        return [
            'slug' => self::slug(basename($file, '.md')),
            'title' => $title,
            'section' => $parts['front']['section'] ?? 'Reference',
            'order' => (int) ($parts['front']['order'] ?? 50),
            'description' => $parts['front']['description'] ?? '',
            'source' => ltrim(str_replace('\\', '/', substr($file, strlen($root))), '/'),
            'md' => $body,
        ];
    }

    /** @return list<array<string, mixed>> */
    private function splitReadme(string $text, array $meta, string $name): array
    {
        $text = str_replace("\r\n", "\n", $text);
        $chunks = preg_split('/^(?=## )/m', $text) ?: [];
        $pages = [];
        $placing = $meta['readme'] ?? [];
        foreach ($chunks as $i => $chunk) {
            if (trim($chunk) === '') continue;
            if ($i === 0) {
                $pages[] = ['slug' => 'overview', 'title' => 'Overview', 'section' => 'Start', 'order' => 0, 'description' => 'What CastFramework is and what it gives you.',
                    'source' => $name, 'md' => (string) preg_replace('/\A# .+\n+/', '', $chunk, 1)];
                continue;
            }
            preg_match('/^## (.+)$/m', $chunk, $m);
            $heading = trim($m[1]);
            [$section, $order] = ($placing[$heading] ?? ['Reference']) + [1 => 50];
            if ($section === '_skip') continue;
            $pages[] = ['slug' => self::slug($heading), 'title' => trim((string) preg_replace('/[`]/', '', $heading)), 'section' => $section, 'order' => (int) $order,
                'description' => '', 'source' => $name . '#' . self::slug($heading), 'md' => (string) preg_replace('/\A## .+\n+/', '', $chunk, 1)];
        }
        return $pages;
    }

    /** @return list<string> heading texts (outside code fences) */
    private function headings(string $md): array
    {
        $out = [];
        $fence = false;
        foreach (explode("\n", $md) as $line) {
            if (preg_match('/^```/', $line)) $fence = !$fence;
            if (!$fence && preg_match('/^#{2,4} (.+)$/', $line, $m)) $out[] = $m[1];
        }
        return $out;
    }

    private function rewriteLinks(string $md, string $current): string
    {
        $pageSlugs = array_column($this->pages, 'slug');
        return (string) preg_replace_callback('/\]\(([^)\s]+)\)/', function (array $m) use ($current, $pageSlugs) {
            $url = $m[1];
            if (preg_match('#^(https?:|mailto:|/|data:)#i', $url)) return $m[0];
            [$path, $anchor] = array_pad(explode('#', $url, 2), 2, '');
            if ($path === '' && $anchor !== '') {                                   // #anchor: a heading somewhere
                $slug = $this->anchors[$anchor] ?? (in_array($anchor, $pageSlugs, true) ? $anchor : $current);
                return '](#/' . $slug . ($slug === $anchor ? '' : '/' . $anchor) . ')';
            }
            $slug = self::slug(basename($path, '.md'));
            if (str_ends_with($path, '.md') && in_array($slug === 'readme' ? 'overview' : $slug, $pageSlugs, true)) {
                if ($slug === 'readme') {                                           // README.md#anchor: the page that owns the heading
                    $target = $anchor !== '' ? ($this->anchors[$anchor] ?? 'overview') : 'overview';
                    return '](#/' . $target . ($anchor !== '' && $target !== $anchor ? '/' . $anchor : '') . ')';
                }
                return '](#/' . $slug . ($anchor !== '' ? '/' . $anchor : '') . ')';
            }
            return $m[0];                                                           // a file link that is not a page: left as it is
        }, $md);
    }
}
