<?php

declare(strict_types=1);

namespace Cast\Console\Commands;

use Cast\Console\{Command, Input, Output};
use Cast\Core\Config;
use Cast\Support\ComponentDocs;

/**
 * `php cast components`: what every component file says about itself (docblocks and defaults), for people and for tools:
 *
 *   php cast components                       a table
 *   php cast components Btns.Button           one component in full
 *   php cast components --json                machine-readable index (for editors and AI agents)
 *   php cast components --markdown --write=docs/components.md
 *   php cast components --check               exit 1 when the documentation and the code disagree (for CI)
 */
final class ComponentsCommand extends Command
{
    protected string $name = 'components';
    protected string $description = 'List the components with their props, types and descriptions';
    protected array $arguments = [
        'Tag?' => 'Show only this component, e.g. Btns.Button',
    ];
    protected array $options = [
        '--json' => 'Print a machine-readable index (for editors and AI tools)',
        '--markdown' => 'Print a Markdown reference page',
        '--write=PATH' => 'Write the Markdown (or --json) output to this file, relative to the app folder',
        '--check' => 'Exit 1 when a docblock and its code disagree: no description, a documented prop the file never uses, a ??= default without @var, undocumented props',
    ];
    protected array $examples = [
        'php cast components' => 'a table of every component',
        'php cast components Btns.Button' => 'one component in full',
        'php cast components --json' => 'index for tools',
        'php cast components --markdown --write=docs/components.md' => 'write the reference page',
        'php cast components --check' => 'for CI',
    ];

    public function handle(Input $input, Output $output): int
    {
        $ext = (string) Config::get('view.ext', '.cast.php');
        $dir = $this->app->viewsPath() . DIRECTORY_SEPARATOR . trim((string) Config::get('view.components', 'components'), '/\\');
        $components = ComponentDocs::scan([$dir], $ext);

        if ($input->hasOption('check')) return $this->check($components, $output);

        $only = $input->argument(0);
        if ($only !== null && $only !== '') {
            $components = array_values(array_filter($components, fn($c) => $c['tag'] === $only));
            if (!$components) {
                $output->error("No component \"$only\" in " . $this->relative($dir) . '.');
                return 1;
            }
        }

        if ($input->hasOption('json')) return $this->emit($input, $output, $this->json($components));
        if ($input->hasOption('markdown') || is_string($input->option('write'))) return $this->emit($input, $output, $this->markdown($components));

        if (!$components) {
            $output->line('No components found in ' . $this->relative($dir) . '.');
            return 0;
        }
        if ($only) {
            $output->line($this->markdown($components));
            return 0;
        }
        $output->table(['Component', 'Props', 'Description'], array_map(fn($c) => [
            '<' . $c['tag'] . '>',
            $this->propList($c['spec']['props']),
            strtok($c['spec']['description'], "\n") ?: '',
        ], $components));
        return 0;
    }

    private function emit(Input $input, Output $output, string $text): int
    {
        $path = $input->option('write');
        if (is_string($path) && $path !== '') {
            $file = preg_match('#^([a-z]:)?[\\/]#i', $path) ? $path : $this->app->basePath($path);
            if (!is_dir(dirname($file))) mkdir(dirname($file), 0775, true);
            file_put_contents($file, $text);
            $output->info('Wrote ' . $this->relative($file));
            return 0;
        }
        $output->line($text);
        return 0;
    }

    /** @param list<array{tag: string, file: string, spec: array}> $components */
    private function json(array $components): string
    {
        $index = ['components' => array_map(fn($c) => ['tag' => $c['tag'], 'file' => $this->relative($c['file'])] + $c['spec'], $components)];
        return json_encode($index, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . "\n";
    }

    /** @param list<array{tag: string, file: string, spec: array}> $components */
    private function markdown(array $components): string
    {
        $md = "# Components\n\nGenerated by `php cast components --markdown`. Props are written in camelCase; `has-label` and `has_label` mean the same.\n";
        foreach ($components as $c) {
            $spec = $c['spec'];
            $md .= "\n## `<{$c['tag']}>`\n\n";
            if ($spec['deprecated']) $md .= '**Deprecated' . ($spec['deprecated'] === true ? '' : ': ' . $spec['deprecated']) . "**\n\n";
            if ($spec['description'] !== '') $md .= $spec['description'] . "\n\n";
            $md .= 'File: `' . $this->relative($c['file']) . "`\n\n";
            if ($spec['props']) {
                $md .= "| Prop | Type | Required | Default | Description |\n| --- | --- | --- | --- | --- |\n";
                foreach ($spec['props'] as $p) {
                    $cell = fn(string $t) => str_replace(['|', "\n"], ['\\|', ' '], $t);
                    $md .= '| `' . $p['name'] . '` | ' . ($p['type'] !== null ? '`' . $cell($p['type']) . '`' : '') . ' | ' . ($p['required'] ? 'yes' : 'no')
                        . ' | ' . ($p['default'] !== null ? '`' . $cell($p['default']) . '`' : '') . ' | ' . $cell($p['description'])
                        . ($p['values'] ? ' (one of ' . implode(', ', array_map(fn($v) => "`$v`", $p['values'])) . ')' : '') . " |\n";
                }
                $md .= "\n";
            }
            if ($spec['slots']) {
                $md .= "Slots: " . implode(', ', array_map(fn($s) => '`' . $s['name'] . '`' . ($s['description'] !== '' ? ' (' . $s['description'] . ')' : ''), $spec['slots'])) . "\n\n";
            }
            foreach ($spec['examples'] as $example) $md .= "```php\n$example\n```\n\n";
        }
        return rtrim($md) . "\n";
    }

    /** @param list<array{name: string, required: bool}> $props */
    private function propList(array $props): string
    {
        return implode(', ', array_map(fn($p) => $p['name'] . ($p['required'] ? '*' : ''), $props)) ?: '-';
    }

    /**
     * Where the documentation and the code disagree.
     * @param list<array{tag: string, file: string, spec: array}> $components
     */
    private function check(array $components, Output $output): int
    {
        $problems = [];
        foreach ($components as $c) {
            $spec = $c['spec'];
            $source = (string) file_get_contents($c['file']);
            $code = (string) preg_replace('/\/\*\*.*?\*\//s', '', $source);   // the file without its docblocks
            $documented = array_filter($spec['props'], fn($p) => !$p['inferred']);

            if ($spec['description'] === '') $problems[] = "<{$c['tag']}>: no description (add a docblock summary)";
            foreach ($documented as $p) {
                if (!preg_match('/\$' . preg_quote($p['name'], '/') . '\b/', $code)) {
                    $problems[] = "<{$c['tag']}>: \"{$p['name']}\" is documented but the file never uses it";
                }
            }
            if ($documented) {
                foreach ($spec['props'] as $p) {
                    if ($p['inferred']) $problems[] = "<{$c['tag']}>: \"{$p['name']}\" has a default (`??=`) but no @var line";
                }
            } elseif ($spec['props']) {
                $problems[] = "<{$c['tag']}>: props are not documented (add @var lines)";
            }
        }
        if (!$problems) {
            $output->info(count($components) . ' component' . (count($components) === 1 ? '' : 's') . ' checked: the documentation matches the code.');
            return 0;
        }
        foreach ($problems as $p) $output->warn($p);
        $output->error(count($problems) . ' problem' . (count($problems) === 1 ? '' : 's') . '.');
        return 1;
    }

    private function relative(string $path): string
    {
        $base = str_replace('\\', '/', $this->app->basePath()) . '/';
        $path = str_replace('\\', '/', $path);
        return str_starts_with($path, $base) ? substr($path, strlen($base)) : $path;
    }
}
