<?php

declare(strict_types=1);

namespace Cast\Console;

use Cast\Contracts\Command as CommandContract;

/** Renders `php cast help <command>` as text, and the whole command reference as Markdown. */
final class Help
{
    /** @return array{arguments: array<string, string>, options: array<string, string>, examples: array<string, string>} */
    public static function of(CommandContract $command): array
    {
        return $command instanceof Command ? $command->help() : ['arguments' => [], 'options' => [], 'examples' => []];
    }

    /** `php cast migrate:sync [table] [options]` */
    public static function usage(CommandContract $command): string
    {
        $help = self::of($command);
        $usage = 'php cast ' . $command->name();
        foreach (array_keys($help['arguments']) as $arg) {
            $usage .= str_ends_with($arg, '?') ? ' [' . substr($arg, 0, -1) . ']' : " <$arg>";
        }
        return $usage . ($help['options'] ? ' [options]' : '');
    }

    public static function render(CommandContract $command, Output $out): void
    {
        $help = self::of($command);
        $out->line($command->name() . ' - ' . $command->description());
        $out->line();
        $out->line('Usage:');
        $out->line('  ' . self::usage($command));

        if ($help['arguments']) {
            $out->line();
            $out->line('Arguments:');
            foreach ($help['arguments'] as $name => $text) $out->line('  ' . str_pad(rtrim($name, '?') . (str_ends_with($name, '?') ? ' (optional)' : ''), 28) . $text);
        }
        if ($help['options']) {
            $out->line();
            $out->line('Options:');
            foreach ($help['options'] as $flag => $text) $out->line('  ' . str_pad($flag, 28) . $text);
        }
        if ($help['examples']) {
            $out->line();
            $out->line('Examples:');
            $width = max(array_map('strlen', array_keys($help['examples'])));
            foreach ($help['examples'] as $example => $text) $out->line('  ' . ($text !== '' ? str_pad($example, $width) . '   # ' . $text : $example));
        }
        $out->line();
        $out->line('Every command also accepts --help (or -h).');
    }

    /** @param array<string, CommandContract> $commands */
    public static function markdown(array $commands): string
    {
        ksort($commands);
        $md = "# Console commands\n\nGenerated by `php cast help --markdown`. `php cast help <command>` (or `php cast <command> --help`) prints the same for one command.\n";
        foreach ($commands as $name => $command) {
            $help = self::of($command);
            $md .= "\n## `$name`\n\n" . $command->description() . ".\n\n```\n" . self::usage($command) . "\n```\n";
            if ($help['arguments']) {
                $md .= "\n| Argument | |\n| --- | --- |\n";
                foreach ($help['arguments'] as $arg => $text) $md .= '| `' . rtrim($arg, '?') . '`' . (str_ends_with($arg, '?') ? ' (optional)' : '') . ' | ' . str_replace('|', '\\|', $text) . " |\n";
            }
            if ($help['options']) {
                $md .= "\n| Option | |\n| --- | --- |\n";
                foreach ($help['options'] as $flag => $text) $md .= '| `' . $flag . '` | ' . str_replace('|', '\\|', $text) . " |\n";
            }
            if ($help['examples']) {
                $md .= "\n```bash\n";
                foreach ($help['examples'] as $example => $text) $md .= $example . ($text !== '' ? "   # $text" : '') . "\n";
                $md .= "```\n";
            }
        }
        return $md;
    }
}
