<?php

declare(strict_types=1);

namespace Cast\Console;

use Cast\Contracts\Command as CommandContract;

/** Renders `php cast help <command>` as text, and the whole command reference as Markdown. */
final class Help
{
    /** @return array{arguments: array<string, string>, options: array<string, string>, examples: array<string, string>} */
    public static function of(CommandContract $command): array
    {
        return $command instanceof Command ? $command->help() : ['arguments' => [], 'options' => [], 'examples' => []];
    }

    /** `php cast migrate:sync [table] [options]` */
    public static function usage(CommandContract $command): string
    {
        $help = self::of($command);
        $usage = 'php cast ' . $command->name();
        foreach (array_keys($help['arguments']) as $arg) {
            $usage .= str_ends_with($arg, '?') ? ' [' . substr($arg, 0, -1) . ']' : " <$arg>";
        }
        return $usage . ($help['options'] ? ' [options]' : '');
    }

    public static function render(CommandContract $command, Output $out): void
    {
        $help = self::of($command);
        $out->line($out->color($command->name(), 'title') . ' - ' . $command->description());
        $out->line();
        $out->line($out->color('Usage:', 'orange'));
        $out->line('  ' . $out->color(self::usage($command), 'green'));

        if ($help['arguments']) {
            $out->line();
            $out->line($out->color('Arguments:', 'orange'));
            foreach ($help['arguments'] as $name => $text) {
                $label = rtrim($name, '?') . (str_ends_with($name, '?') ? ' (optional)' : '');
                $out->line('  ' . $out->color(str_pad($label, 28), 'blue') . $text);
            }
        }
        if ($help['options']) {
            $out->line();
            $out->line($out->color('Options:', 'orange'));
            foreach ($help['options'] as $flag => $text) $out->line('  ' . $out->color(str_pad($flag, 28), 'green') . $text);
        }
        if ($help['examples']) {
            $out->line();
            $out->line($out->color('Examples:', 'orange'));
            $width = max(array_map('strlen', array_keys($help['examples'])));
            foreach ($help['examples'] as $example => $text) {
                $out->line('  ' . ($text !== '' ? $out->color(str_pad($example, $width), 'green') . '   ' . $out->color('# ' . $text, 'grey') : $out->color($example, 'green')));
            }
        }
        $out->line();
        $out->line($out->color('Every command also accepts --help (or -h).', 'grey'));
    }

    /** @param array<string, CommandContract> $commands */
    public static function markdown(array $commands): string
    {
        ksort($commands);
        $md = "---\ntitle: Console commands\nsection: Tooling\norder: 1\ndescription: Every command, its arguments and flags.\n---\n\n# Console commands\n\nGenerated by `php cast help --markdown`. `php cast help <command>` (or `php cast <command> --help`) prints the same for one command.\n";
        foreach ($commands as $name => $command) {
            $help = self::of($command);
            $md .= "\n## `$name`\n\n" . $command->description() . ".\n\n```\n" . self::usage($command) . "\n```\n";
            if ($help['arguments']) {
                $md .= "\n| Argument | |\n| --- | --- |\n";
                foreach ($help['arguments'] as $arg => $text) $md .= '| `' . rtrim($arg, '?') . '`' . (str_ends_with($arg, '?') ? ' (optional)' : '') . ' | ' . str_replace('|', '\\|', $text) . " |\n";
            }
            if ($help['options']) {
                $md .= "\n| Option | |\n| --- | --- |\n";
                foreach ($help['options'] as $flag => $text) $md .= '| `' . str_replace('|', '\\|', $flag) . '` | ' . str_replace('|', '\\|', $text) . " |\n";
            }
            if ($help['examples']) {
                $md .= "\n```bash\n";
                foreach ($help['examples'] as $example => $text) $md .= $example . ($text !== '' ? "   # $text" : '') . "\n";
                $md .= "```\n";
            }
        }
        return $md;
    }
}
